# Generated by Django 4.2.14 on 2025-09-16 15:33

import artifacts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=artifacts.models.originals_path)),
                ('processed_image', models.ImageField(upload_to=artifacts.models.processed_path)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=artifacts.models.zips_path)),
                ('geojson_file', models.FileField(blank=True, null=True, upload_to=artifacts.models.geojson_path)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
