# Generated by Django 4.2.14 on 2025-09-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=256)),
                ('input_dir', models.CharField(blank=True, max_length=512)),
                ('result_dir', models.CharField(blank=True, max_length=512)),
                ('zip_path', models.CharField(blank=True, max_length=512)),
                ('outputs_zip_path', models.CharField(blank=True, max_length=512)),
                ('geojson_path', models.CharField(blank=True, max_length=512)),
                ('input_images', models.JSONField(blank=True, default=list)),
                ('output_images', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
