"""
Django settings for tree_project project.
Generated by 'django-admin startproject' using Django 3.2.4.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c0ao!%251&wv9cqd)evqo#j%w$zgt561=zk3w4v(0&0ew0s3s('

# SECURITY WARNING: don’t run with debug turned on in production!
DEBUG = True

# NOTE: ALLOWED_HOSTS entries must be hostnames/IPs, not full URLs
ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1", "194.180.176.140"]

# ---- CORS ----
INSTALLED_APPS = [
    "corsheaders",                     # corsheaders app
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tree_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",   # CORS must be high in the stack
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Allow your Vite frontends to call Django
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4173",          # <--- added this
    "http://localhost:5173",
    "http://192.168.50.214:5173",
    "http://192.168.100.73:5173",
    "http://192.168.100.11:5173",
    "http://194.180.176.140:5173",
]

ROOT_URLCONF = "tree_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tree_project.wsgi.application"

# File upload limits (optional — your values are extremely large; keep only if intentional)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2**31 - 1
DATA_UPLOAD_MAX_NUMBER_FILES = 1000
FILE_UPLOAD_MAX_MEMORY_SIZE = 2**31 - 1

# Database (SQLite by default)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ---- Static & Media ----
STATIC_URL = "/static/"
# Directory you keep your generated artifacts, zips, etc. during dev
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# For production collectstatic (optional but good to have)
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# If you ever write files outside /static, you can serve them via MEDIA*
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
